### ISSUE TITLE
The downloaded shanghaitech dataset is a video. How to convert it into a frame? Or can you put a download link to the Shanghai dataset?

### ISSUE THREAD

**Issue by xiximin** [cvlab-yonsei/MNAD#29]

**Comment by saypadith** [comment]
Using FFmpeg
Please refer to this: https://superuser.com/a/1346333

**Comment by william-yl-gu** [comment]
Just curious, do you set the fps during the conversion?

**Comment by saypadith** [comment]
> Just curious, do you set the fps during the conversion?

This is my code: I set it to 24fps (-r 24/1) as it shows in the detail of the video.

`
for %%F in (*.avi) do (
    If not Exist "%%~nF" MkDir "%%~nF"
    ffmpeg -i %%F -r 24/1 -qscale:v 2 %%~nF\%%~nF-%%3d.jpg
)
`

**Comment by xiximin** [comment]
Thank you. I'll try.

**Comment by xiximin** [comment]
An error occurred while training the Shanghai dataset.
Traceback (most recent call last):
  File "Train.py", line 154, in <module>
    for j,(imgs) in enumerate(train_batch):
  File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/userfolder/code/projects1/MNAD/FFPMem/model/utils.py", line 71, in __getitem__
    image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
IndexError: list index out of range

**Comment by TanMing11** [comment]
> > Just curious, do you set the fps during the conversion?
> 
> This is my code: I set it to 24fps (-r 24/1) as it shows in the detail of the video.
> 
> ```
> for %%F in (*.avi) do (
>     If not Exist "%%~nF" MkDir "%%~nF"
>     ffmpeg -i %%F -r 24/1 -qscale:v 2 %%~nF\%%~nF-%%3d.jpg
> )
> ```

hello，could you tell me how to use this code?

**Comment by yangyangtiaoguo** [comment]
> An error occurred while training the Shanghai dataset.
> Traceback (most recent call last):
> File "Train.py", line 154, in
> for j,(imgs) in enumerate(train_batch):
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in **next**
> return self._process_data(data)
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> data.reraise()
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
> raise self.exc_type(msg)
> IndexError: Caught IndexError in DataLoader worker process 1.
> Original Traceback (most recent call last):
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/root/userfolder/code/projects1/MNAD/FFPMem/model/utils.py", line 71, in **getitem**
> image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
> IndexError: list index out of range



> An error occurred while training the Shanghai dataset.
> Traceback (most recent call last):
> File "Train.py", line 154, in
> for j,(imgs) in enumerate(train_batch):
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in **next**
> return self._process_data(data)
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> data.reraise()
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
> raise self.exc_type(msg)
> IndexError: Caught IndexError in DataLoader worker process 1.
> Original Traceback (most recent call last):
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/root/userfolder/code/projects1/MNAD/FFPMem/model/utils.py", line 71, in **getitem**
> image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
> IndexError: list index out of range

Hello, I also encountered this problem, how did you solve it? Thanks!

**Comment by TanMing11** [comment]
> > An error occurred while training the Shanghai dataset.
> > Traceback (most recent call last):
> > File "Train.py", line 154, in
> > for j,(imgs) in enumerate(train_batch):
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in **next**
> > return self._process_data(data)
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> > data.reraise()
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
> > raise self.exc_type(msg)
> > IndexError: Caught IndexError in DataLoader worker process 1.
> > Original Traceback (most recent call last):
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> > data = fetcher.fetch(index)
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/root/userfolder/code/projects1/MNAD/FFPMem/model/utils.py", line 71, in **getitem**
> > image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
> > IndexError: list index out of range
> 
> > An error occurred while training the Shanghai dataset.
> > Traceback (most recent call last):
> > File "Train.py", line 154, in
> > for j,(imgs) in enumerate(train_batch):
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in **next**
> > return self._process_data(data)
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> > data.reraise()
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
> > raise self.exc_type(msg)
> > IndexError: Caught IndexError in DataLoader worker process 1.
> > Original Traceback (most recent call last):
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> > data = fetcher.fetch(index)
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/root/userfolder/code/projects1/MNAD/FFPMem/model/utils.py", line 71, in **getitem**
> > image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
> > IndexError: list index out of range
> 
> Hello, I also encountered this problem, how did you solve it? Thanks!

hello，did you solve it?
