### ISSUE TITLE
An error occurred while training the Shanghai dataset

### ISSUE THREAD

**Issue by xiximin** [cvlab-yonsei/MNAD#31]
Traceback (most recent call last):
File "Train.py", line 154, in
for j,(imgs) in enumerate(train_batch):
File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in next
return self._process_data(data)
File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
data.reraise()
File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
data = fetcher.fetch(index)
File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/root/userfolder/code/projects1/MNAD/FFPMem/model/utils.py", line 71, in getitem
image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
IndexError: list index out of range

**Comment by Yuan98Yu** [comment]
find this line(line 62) in file 'model/utils.py'

**Comment by renqi1120** [comment]
you need modify shanghai's labels  file 《frame_labels_shanghai.npy》,Incorrect label format.

**Comment by huyi1998** [comment]
> you need modify shanghai's labels file 《frame_labels_shanghai.npy》,Incorrect label format.

可以看看你的代码吗，我不知道为啥，train老是遇到各种错误

**Comment by Celinewxy** [comment]
> 回溯（最近一次调用最后一次）： 文件“Train.py”，第 154 行， for j,(imgs) in enumerate(train_batch)： 文件“/root/userfolder/software/anaconda3/envs/MemG/lib/python3. 6/site-packages/torch/utils/data/dataloader.py”，第 819 行，在下一个 返回 self._process_data(data) 文件“/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/ site-packages/torch/utils/data/dataloader.py”，第 846 行，在 _process_data data.reraise() 文件“/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/ torch/_utils.py”，第 369 行，在重新引发中 raise self.exc_type(msg) IndexError：在 DataLoader 工作进程 1 中捕获 IndexError。 原始回溯（最近一次调用）： 文件“/root/userfolder/software/anaconda3/envs /MemG/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py”，第 178 行，在 _worker_loop data = fetcher.fetch(index) 文件“/root/userfolder/software/anaconda3/ envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py​​”，第 44 行，在获取 数据 = [self.dataset[idx] for idx in possible_batched_index] 文件“/root /userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py​​”，第 44 行，在 data = [self.dataset[idx] for idx in possible_batched_index] 文件“/root/userfolder/code/projects1/MNAD/FFPMem/model/utils.py”，第 71 行，在 getitem image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width) IndexError: 列表索引超出范围

请问你解决这个问题了么

**Comment by yinyexingchen** [comment]
> > 回溯（最近一次调用最后一次）： 文件“Train.py”，第 154 行， for j,(imgs) in enumerate(train_batch)： 文件“/root/userfolder/software/anaconda3/envs/MemG/lib/python3. 6/site-packages/torch/utils/data/dataloader.py”，第 819 行，在下一个 返回 self._process_data(data) 文件“/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/ site-packages/torch/utils/data/dataloader.py”，第 846 行，在 _process_data data.reraise() 文件“/root/userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/ torch/_utils.py”，第 369 行，在重新引发中 raise self.exc_type(msg) IndexError：在 DataLoader 工作进程 1 中捕获 IndexError。 原始回溯（最近一次调用）： 文件“/root/userfolder/software/anaconda3/envs /MemG/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py”，第 178 行，在 _worker_loop data = fetcher.fetch(index) 文件“/root/userfolder/software/anaconda3/ envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py​​”，第 44 行，在获取 数据 = [self.dataset[idx] for idx in possible_batched_index] 文件“/root /userfolder/software/anaconda3/envs/MemG/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py​​”，第 44 行，在 data = [self.dataset[idx] for idx in possible_batched_index] 文件“/root/userfolder/code/projects1/MNAD/FFPMem/model/utils.py”，第 71 行，在 getitem image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width) IndexError: 列表索引超出范围
> 
> 请问你解决这个问题了么

你好，请问你解决这个问题了吗
