### ISSUE TITLE
AttributeError: 'convAE' object has no attribute 'clone'

### ISSUE THREAD

**Issue by weibienao** [cvlab-yonsei/MNAD#7]
I used pytorch1.1.0,and no change the code,but show this issue:

Traceback (most recent call last):
  File "/home/lh/MNAD-master1/Evaluate.py", line 121, in <module>
    m_items_test = m_items.clone()
  File "/home/lh/anaconda3/envs/torch11/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'convAE' object has no attribute 'clone'

**Comment by weibienao** [comment]
My low-level mistake
